baseURL = 'https://nohawrites.com/'
languageCode = 'en-us'
title = 'Noha Writes'
theme = 'PaperMod'

relativeURLs = true
canonifyURLs = false

[pagination]
  pagerSize = 5


[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  mainSections = ["blog"]
  showRecentPosts = true

[params.profileMode]
  enabled = true
  title = "Noha Writes"
  subtitle = "Cybersecurity Enthusiast and Freelance Writer"
  imageUrl = "images/profile.jpg"


[[params.profileMode.buttons]]
name = "Blog"
url = "/blog/"

[[params.profileMode.buttons]]
name = "Work With Me"
url = "/work-with-me/"